### ISSUE TITLE
Create a term for the detector used.

### ISSUE THREAD

**Issue by uermel** [GullyBurns/cryoeto#1]
For new term requests, please provide the following information:

## Preferred term label

Direct Electron Detector

## Textual definition

An electron microscopy camera capable of measuring electron incidences without relying on photon scintillation.

## Suggested parent term

image creation device

**Comment by GullyBurns** [comment]
Resolved by [4cb832](https://github.com/GullyBurns/cryoeto/commit/4cb832a2a8ad9014b7feda9959a61c72b4a9deba]
